spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/plotpro
    username: prakulka
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080

# Application specific properties
plotpro:
  app:
    jwtSecret: 9ihwq1212ioj39021hu1p290oi123wrq32
    jwtExpirationMs: 86400000